#!/usr/bin/env bash

set -e

# $@ = All command line arguments
# $1 = First command line argument, etc.
# ${*:2} Every parameter after the first one.

args=$@
params=${*:2}
command=$1

function drush() {
    docker-compose exec -T php www/bin/drush @default.dev $params
    return $?
}

function install() {
    docker-compose up -d --build
    echo Database is initializing...
    docker-compose logs db
    docker-compose logs -f db | while read LOGLINE
    do
        [[ "${LOGLINE}" == *"mysqld: ready for connections."* ]] && killall docker-compose && exit 0
    done
    if [ -f db/database.sql.gz ] || [ -f db/database.sql ]; then
        if [ -f db/database.sql.gz ]; then gunzip db/database.sql.gz; fi
        docker-compose exec -T php drush @default.dev sql-drop -yv
        docker-compose exec -T php /bin/sh -c "mysql -h db -u drupal -pdrupal drupal < /var/www/html/db/database.sql"
        provision;
    else
        docker-compose exec -T php /bin/sh -c "chmod 777 /var/www/html/www/web/sites/default"
        docker-compose exec -T php composer --working-dir=www install -n
        docker-compose exec -T php www/bin/drush @default.dev si -y minimal --db-url='mysql://drupal:drupal@db:3306/drupal' --site-name="DockerDrop, a Docker Training Site" --config-dir="../config/sync" --site-mail=admin@example.com --account-name=admin --account-pass=admin
    fi
    return $?
}

function provision() {
    docker-compose exec -T php www/bin/drush @default.dev cim -y --source=/var/www/html/www/config/sync
    docker-compose exec -T php www/bin/drush @default.dev updb -y
    docker-compose exec -T php www/bin/drush @default.dev entup -y
}

function cex() {
    docker-compose exec -T php www/bin/drush @default.dev cim -y --source=/var/www/html/www/config/sync
}

function init() {
    docker-compose ps
    docker-compose exec -T php www/bin/drush @default.dev uli
    return $?
}
function clean() {
    docker-compose down && exit 0
    ## Note: change this to the volume(s) for your project
    docker volume rm dockerdrop_mysql-data && exit 0
    return $?
}
function dbdump() {
    docker-compose exec -T php www/bin/drush @default.dev sql-dump --result-file=/var/www/html/db/database.sql --gzip
}

$command $params;

exit $?